### ISSUE TITLE
serialization/unordered_map.hpp?

### ISSUE THREAD

**Issue by brendanf** [eddelbuettel/bh#102]
I am aware that the boost serialization library does not function without some compiled components.  However, most of the headers are included in BH, with the exception that `serialization/unordered_map.hpp` is not present.  Is there a particular reason for that or is it just an oversight?

**Comment by eddelbuettel** [comment]
So what happens is that as you already allude to 
- we actively constrain to Boost components that are header-only, no linking ever
- we use the `bcp` copy command for those listed libraries (list in the README and DESCRIPTION and script)
- because 'Boost uses Boost' the list (maybe partial) subdirectories is larger than the list of projects because 'a,b,c' may also need (parts of) 'd,e,f'.

I suspect that is what happened here.  You can posssibly get by for by just includnig the one matching file (from the same Boost release) in your package.  We could then look into maybe explicitly copying that one file if it helps.   (As I likely cannot / will not take 'serialization' wholesale as it may require linking.)

There is a bit of a middle gound.  Some of the libraries would require linking for some operations but 'mostly' work without it.  'date_time' is an example: we get pretty much everything _but formatting to string / output_ without linking.

**Comment by brendanf** [comment]
It turns out that when I added that one, then it complained about another (`boost/serialization/unordered_collections_save_imp.hpp`).  Since the only Boost functionality I am using in my package are things that do require linking anyway (serialization and IO to gzipped files) the most efficient solution is probably for me to just include all the required files in the package, rather than including some and depending on BH for others.

**Comment by eddelbuettel** [comment]
Yes. Separation of concern is good.  I hope the local copy of what you need from Boost is not getting to big though.
