### ISSUE TITLE
A request to add  timer/include/boost/progress.hpp 

### ISSUE THREAD

**Issue by wush978** [eddelbuettel/bh#84]
Hi Dirk,

I noticed a warning message related to `progress.hpp`  recently:

```
/usr/local/lib/R/site-library/BH/include/boost/progress.hpp:23:1: warning: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> or <boost/timer/progress_display.hpp> instead. [-W#pragma-messages]
```

As discussed in https://github.com/boostorg/timer/issues/12 , there is a file `timer/include/boost/progress.hpp` now and it is a replacement of `boost/pgoress.hpp`.

However, the BH package does not contain the file `timer/include/boost/progress.hpp`.

Could you add this file to BH, so we could migrate the class and prevent the warning message?

Best,
Wush

**Comment by eddelbuettel** [comment]
Hi Wush,

Because Boost (and BH) are so big I tend to update only yearly in December.  So chances we may get this with the next official version which should be bh 1.81 based ob Boost 1.81 due December.  Would that be good enough?  It is not really under my control whether the Boost folks include this or not.

Now the issue https://github.com/boostorg/timer/issues/12 you list is from a few years ago and references Boost 1.72 but then links to a commit tagged 1.80.  So it depends on whether Boost gets this out with 1.81. 

Hope this helps,   Dirk

**Comment by wush978** [comment]
That looks good to me. Thanks for your prompt reply!

**Comment by eddelbuettel** [comment]
PR #87, currently still open, has Boost 1.81.0 released yesterday.

**Comment by wush978** [comment]
Thanks for your follow-up. Please let me know if there is anything that I can help with.

**Comment by eddelbuettel** [comment]
Thanks -- we have to wait a little to sort a small amount of changes out -- see #88 which also has pointers to the not-yet-for-CRAN release 1.81.0-0.

**Comment by eddelbuettel** [comment]
And BH 1.81.0-1 is now on CRAN so you have the progress header at long last!

**Comment by wush978** [comment]
Thank you!

**Comment by eddelbuettel** [comment]
:cry: 

Yes please.

**Comment by eddelbuettel** [comment]
This is now (finally !!) in BH 1.84.0.  There are very minor repurcussions with five packages (including yours which of course still throws the NOTE I prevented you from updating) so this will only be on CRAN in January after which time you can update yours. Until then you can get it from here, or from the r-universe builds and I may add it to the ghrr drat as well so that you can test your change.

Or, come to think about it, you could even test the change and maybe `#if` define a solution that works before and after?
